export const listItemGetstarted = [
  {
    title: "List Equipments",
    description: `Think of all the great things 
            you have to rent out in your home from 
            tools to toys everything in -between`,
  },
  {
    title: "Add Photos",
    description: `Think of all the great things 
            you have to rent out in your home from 
            tools to toys everything in -between`,
  },
  {
    title: "Update Profile",
    description: `Think of all the great things 
            you have to rent out in your home from 
            tools to toys everything in -between`,
  },
  {
    title: "Quick Response",
    description: `Think of all the great things 
            you have to rent out in your home from 
            tools to toys everything in -between`,
  },
];

export const listItemCat = [
  {
    cat_img: "/images/list-item/category1.png",
    title: "Cameras",
  },
  {
    cat_img: "/images/list-item/category2.png",
    title: "Drones",
  },
  {
    cat_img: "/images/list-item/category3.png",
    title: "Lightings",
  },
  {
    cat_img: "/images/list-item/category4.png",
    title: "Camera Accessories",
  },
  {
    cat_img: "/images/list-item/category5.png",
    title: "Tripod Support",
  },
  {
    cat_img: "/images/list-item/category6.png",
    title: "Electricals",
  },
  {
    cat_img: "/images/list-item/category7.png",
    title: "Audio",
  },
  {
    cat_img: "/images/list-item/category8.png",
    title: "VR (oculus)",
  },
];

export const listItemRenting = [
  {
    title: "Arrange",
    description: `Make sure you’re available for handovers on the days being booked by the borrower.`,
  },
  {
    title: "Accept",
    description: `Once a user is verified by our risk algorithms and our team, you’ll receive a request to accept.`,
  },
  {
    title: "Handover",
    description: `Take a few pictures of the items and hand them over to the borrower.`,
  },
  {
    title: "Payment",
    description: `24 hours after the rental starts, we’ll pay out your earnings to your account.`,
  },
];

// How it works

export const hiwBeforeRental = [
  {
    icon: "/images/before-rental/nearby.svg",
    title: "Find An Item Nearby",
    description: `Search for the items you're looking for and filter by location_name.`,
  },
  {
    icon: "/images/before-rental/verify.svg",
    title: "Request & Verify",
    description: `Send a request to the lender for the dates you’d like the items. Your booking is only confirmed when the owner accepts your request.`,
  },
  {
    icon: "/images/before-rental/heart.svg",
    title: "Arrange Handover with Owner",
    description: `Use chat to arrange convenient times to pick up the item and ask any questions you might have.`,
  },
];

export const hiwDuringRental = [
  {
    icon: "/images/during-rental/during1.png",
    title: "Enjoy Rentals & Returns On Time",
    description: `Make the most of your time with
        the item and then return it safely
        to the owner at the end of the rental.`,
  },
  {
    icon: "/images/during-rental/during2.png",
    title: "Need More Time?",
    description: `Be sure to check in with the lender and book
        extra days if the item is available 
        and you want to keep it for longer.`,
  },
];

export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];
// export const tripodInLagos = [
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod1.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod2.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod3.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod4.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod4.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod1.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod2.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod3.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod4.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod4.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod1.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod2.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     image: "/images/tripods/tripod3.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod4.png",
//   },
//   {
//     title: "Picknfix",
//     description: "Video Camera REWK17",
//     price: 300000,
//     location_name: "Sholmolu, Lagos",
//     rating: 4.5,
//     img_url: "/images/tripods/tripod4.png",
//   },
// ];

export const topCities = [
  {
    city: "Lagos",
    lat: 6.45,
    lng: 3.4,
  },
  {
    city: "Kano",
    lat: 12.0,
    lng: 8.5167,
  },
  {
    city: "Ibadan",
    lat: 7.3964,
    lng: 3.9167,
  },
  {
    city: "Onitsha",
    lat: 6.1667,
    lng: 6.7833,
  },
  {
    city: "Owerri",
    lat: 5.4833,
    lng: 7.0333,
  },
  {
    city: "Abuja",
    lat: 9.0556,
    lng: 7.4914,
  },
  {
    city: "Maiduguri",
    lat: 11.8333,
    lng: 13.15,
  },
  {
    city: "Benin City",
    lat: 6.3176,
    lng: 5.6145,
  },
  {
    city: "Ikare",
    lat: 7.5304,
    lng: 5.76,
  },
  {
    city: "Ogbomoso",
    lat: 8.1333,
    lng: 4.25,
  },
];
